# Generated by Django 2.2 on 2020-11-02 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=120)),
                ('vacancy', models.IntegerField(blank=True, null=True)),
                ('job_context', models.CharField(blank=True, max_length=500, null=True)),
                ('job_resposibility', models.CharField(blank=True, max_length=500, null=True)),
                ('employment_status', models.CharField(blank=True, max_length=500, null=True)),
                ('educational_req', models.CharField(blank=True, max_length=500, null=True)),
                ('experience_req', models.CharField(blank=True, max_length=500, null=True)),
                ('additional_req', models.CharField(blank=True, max_length=500, null=True)),
                ('job_location', models.CharField(blank=True, max_length=500, null=True)),
                ('salaray', models.IntegerField(blank=True, null=True)),
                ('compensation', models.CharField(blank=True, max_length=500, null=True)),
                ('application_deadline', models.DateField(auto_now=True)),
                ('application_procedure', models.DecimalField(blank=True, decimal_places=2, max_digits=2, null=True)),
                ('publish_on', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Company.Company')),
            ],
            options={
                'ordering': ['-publish_on'],
            },
        ),
    ]
