# Generated by Django 2.2 on 2020-11-04 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Job', '0003_auto_20201104_1246'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='job_resposibility',
            new_name='job_responsibility',
        ),
    ]
