# Generated by Django 2.2 on 2020-11-04 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job', '0004_auto_20201104_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='additional_req',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='application_procedure',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='compensation',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='educational_req',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='experience_req',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_context',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_location',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_responsibility',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
    ]
