# Generated by Django 2.2 on 2020-11-04 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Job', '0007_auto_20201104_1912'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='user',
            new_name='company_username',
        ),
    ]
