# Generated by Django 2.2 on 2020-11-05 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job', '0008_auto_20201104_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='draft',
            field=models.BooleanField(default=False),
        ),
    ]
