# Generated by Django 2.2 on 2020-11-08 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Job', '0011_auto_20201105_1330'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='company_username',
            new_name='user',
        ),
    ]
