# Generated by Django 2.2 on 2020-11-10 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job', '0013_auto_20201109_0211'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
