# Generated by Django 2.2 on 2020-11-11 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job', '0017_auto_20201111_0452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
