# Generated by Django 2.2 on 2020-11-03 03:31

import Company.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.TextField()),
                ('address', models.TextField()),
                ('post_code', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=120)),
                ('company_title', models.CharField(blank=True, max_length=120, null=True)),
                ('company_profile_image', models.ImageField(blank=True, null=True, upload_to=Company.models.upload_location)),
                ('company_info', models.TextField(blank=True, null=True)),
                ('company_email', models.EmailField(max_length=254)),
                ('company_country', models.CharField(max_length=20)),
                ('company_web_link', models.URLField(blank=True, null=True)),
                ('company_ratting', models.DecimalField(blank=True, decimal_places=2, max_digits=2, null=True)),
                ('company_review', models.CharField(blank=True, max_length=150, null=True)),
                ('company_password', models.CharField(max_length=30)),
                ('profile_created', models.DateTimeField(auto_now_add=True)),
                ('is_company', models.BooleanField(default=False)),
                ('company_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Company.Address')),
                ('company_username', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-profile_created'],
            },
        ),
    ]
