# Generated by Django 2.2 on 2020-11-03 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='is_company',
        ),
    ]
