# Generated by Django 2.2 on 2020-11-03 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0002_remove_company_is_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_company',
            field=models.BooleanField(default=False),
        ),
    ]
