# Generated by Django 2.2 on 2020-11-03 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0003_company_is_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_password',
            field=models.CharField(max_length=100),
        ),
    ]
