# Generated by Django 2.2 on 2020-11-09 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0006_auto_20201108_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_password',
            field=models.CharField(max_length=30),
        ),
    ]
