# Generated by Django 2.2 on 2020-11-09 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0007_auto_20201109_0218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='company_password',
        ),
        migrations.AlterField(
            model_name='company',
            name='is_company',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='profile_created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
