# Generated by Django 2.2 on 2020-11-02 12:24

import Employee.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.TextField()),
                ('address', models.TextField()),
                ('post_code', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Portfulio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('details', models.TextField(blank=True, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to=Employee.models.upload_location)),
            ],
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github', models.URLField(blank=True, null=True)),
                ('stackoverflow', models.URLField(blank=True, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('facebook', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FollowRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activated', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('followers', models.ManyToManyField(blank=True, related_name='is_following', to=settings.AUTH_USER_MODEL)),
                ('following', models.ManyToManyField(blank=True, related_name='following', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_first_name', models.CharField(max_length=120)),
                ('emp_last_name', models.CharField(max_length=120)),
                ('emp_position_title', models.CharField(blank=True, max_length=120, null=True)),
                ('emp_profile_image', models.ImageField(blank=True, null=True, upload_to=Employee.models.upload_location)),
                ('emp_info', models.TextField(blank=True, null=True)),
                ('emp_email', models.EmailField(max_length=254)),
                ('emp_country', models.CharField(max_length=20)),
                ('emp_skills', models.TextField()),
                ('emp_resume', models.FileField(blank=True, null=True, upload_to=Employee.models.upload_location)),
                ('emp_ratting', models.DecimalField(blank=True, decimal_places=2, max_digits=2, null=True)),
                ('emp_review', models.CharField(blank=True, max_length=150, null=True)),
                ('emp_password', models.CharField(max_length=30)),
                ('profile_created', models.DateTimeField(auto_now_add=True)),
                ('emp_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Employee.Address')),
                ('emp_portfulio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Employee.Portfulio')),
                ('emp_social_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Employee.SocialLink')),
                ('emp_username', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-profile_created'],
            },
        ),
    ]
