# Generated by Django 2.2 on 2020-11-03 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0002_auto_20201103_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='password2',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
