# Generated by Django 2.2 on 2020-11-03 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0003_employee_password2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='emp_password',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='password2',
        ),
    ]
