# Generated by Django 2.2 on 2020-11-03 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0004_auto_20201103_1450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='is_employee',
        ),
    ]
