# Generated by Django 2.2 on 2020-11-03 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0005_remove_employee_is_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_employee',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
