# Generated by Django 2.2 on 2020-11-03 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0006_employee_is_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='emp_password',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
