# Generated by Django 2.2 on 2020-11-10 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0010_auto_20201110_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='emp_experience',
            field=models.TextField(blank=True, null=True),
        ),
    ]
